version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - 2181:2181
    logging: { driver: none }

  server:
    image: quay.io/nordstrom/confluent-kafka-broker:5.1.0
    ports:
    - 9092:9092
    - 9093:9093
    - 9011:9011
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "INSECURE://0.0.0.0:9092,SECURE://0.0.0.0:9093,REPLICATION://0.0.0.0:19093"
      KAFKA_ADVERTISED_LISTENERS: "INSECURE://localhost:9092,SECURE://localhost:9093,REPLICATION://server:19093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSECURE:PLAINTEXT,SECURE:SSL,REPLICATION:SSL"
      KAFKA_INTER_BROKER_LISTENER_NAME: "REPLICATION"
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 10
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"

      KAFKA_LISTENER_NAME_SECURE_SSL_KEYSTORE_LOCATION: "/var/private/server.jks"
      KAFKA_LISTENER_NAME_SECURE_SSL_KEYSTORE_PASSWORD: "changeme"

      KAFKA_LISTENER_NAME_REPLICATION_SSL_TRUSTSTORE_LOCATION: "/var/private/truststore.jks"
      KAFKA_LISTENER_NAME_REPLICATION_SSL_KEYSTORE_LOCATION: "/var/private/server.jks"
      KAFKA_LISTENER_NAME_REPLICATION_SSL_KEYSTORE_PASSWORD: "changeme"
    volumes:
    - ./server.jks:/var/private/server.jks
    - ./truststore.jks:/var/private/truststore.jks
    depends_on: [zookeeper]
